server:
  port: 8080
  
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: false
  datasource: 
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:testdb;sql.syntax_ora=true
    username: sa
    password: 
    